"""Write interactive/genome-fold.js: the predicted structure the genome stage draws.

The genome stage follows the first 180 bases of the cas12a gene of
*Francisella novicida* U112. Its `#fold` scene shows where the 60 residues
those bases spell sit in the whole protein, and that needs the protein: one
alpha-carbon per residue, 1,300 of them, from the AlphaFold Protein Structure
Database's model of UniProt A0Q7Q2.

This script fetches that model, checks it against the SHA-256 pinned below,
and writes the coordinates out as a literal the page loads with a plain
`<script src>` -- so the stage still fetches nothing at run time. Standard
library only, so it runs with a bare `python3`:

    python3 scripts/gen_genome_fold.py

It needs the network, which is why nothing in CI runs it; the pin is what
stops the literal silently regenerating from a different model. When the
database publishes a new version, change `VERSION` and `SHA256` together, rerun,
and update the ledger in interactive/genome-scenes/README.md and the numbers
tests/genome_core.test.cjs pins. The file is deterministic for a given model:
`FETCHED` is a constant here, not today's date.

The model is CC BY 4.0 (Jumper et al. 2021; Varadi et al. 2024); the header
this script writes carries the attribution.
"""

from __future__ import annotations

import hashlib
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "interactive" / "genome-fold.js"
UA = "tensors-workshop/1.0 (https://github.com/project-delphi/tensors-workshop)"

ACCESSION = "A0Q7Q2"
MODEL = f"AF-{ACCESSION}-F1"
VERSION = 6
URL = f"https://alphafold.ebi.ac.uk/files/{MODEL}-model_v{VERSION}.pdb"
SHA256 = "fabfed1a6c7cb6645b4592bbaabb4fa855e25187914548baac8c0cf570fb1df1"
FETCHED = "2026-10-01"

THREE = {
    "ALA": "A", "CYS": "C", "ASP": "D", "GLU": "E", "PHE": "F", "GLY": "G", "HIS": "H",
    "ILE": "I", "LYS": "K", "LEU": "L", "MET": "M", "ASN": "N", "PRO": "P", "GLN": "Q",
    "ARG": "R", "SER": "S", "THR": "T", "VAL": "V", "TRP": "W", "TYR": "Y",
}  # fmt: skip


def fetch() -> bytes:
    req = urllib.request.Request(URL, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=120) as resp:
        body = resp.read()
    got = hashlib.sha256(body).hexdigest()
    if got != SHA256:
        sys.exit(
            f"{URL}\n  has SHA-256 {got},\n  not the pinned {SHA256}.\n"
            "The database has changed the model. Read the docstring before changing the pin."
        )
    return body


def alpha_carbons(
    pdb: str,
) -> tuple[str, list[tuple[float, float, float]], list[float]]:
    """One alpha-carbon per residue: its letter, its position and its pLDDT.

    PDB is a fixed-column format: the atom name is columns 13-16, the residue
    name 18-20, x, y and z 31-54, and AlphaFold writes the residue's pLDDT
    where an experimental file keeps the B-factor, columns 61-66.
    """
    seq, xyz, plddt = [], [], []
    for line in pdb.splitlines():
        if line.startswith("ATOM") and line[12:16].strip() == "CA":
            seq.append(THREE[line[17:20]])
            xyz.append((float(line[30:38]), float(line[38:46]), float(line[46:54])))
            plddt.append(float(line[60:66]))
    return "".join(seq), xyz, plddt


def wrap(items: list[str], per_line: int, indent: str) -> str:
    rows = [items[i : i + per_line] for i in range(0, len(items), per_line)]
    return ",\n".join(indent + ", ".join(row) for row in rows)


def render(seq: str, xyz: list[tuple[float, float, float]], plddt: list[float]) -> str:
    coords = [f"{v:.1f}" for point in xyz for v in point]
    seq_lines = [seq[i : i + 60] for i in range(0, len(seq), 60)]
    seq_js = " +\n".join(f'      "{row}"' for row in seq_lines)
    return f"""/*
 * genome-fold.js -- GENERATED by scripts/gen_genome_fold.py. Do not hand-edit.
 *
 * The predicted structure of Cas12a, the protein the genome stage's gene
 * encodes: one alpha-carbon per residue, {len(seq)} of them. The stage's 60
 * residues are the first 60 here, and tests/genome_core.test.cjs requires
 * that -- `seq` below must begin with the core's PROTEIN.
 *
 * model    {MODEL}, version {VERSION} (AlphaFold Protein Structure Database)
 * source   {URL}
 * sha256   {SHA256}
 * fetched  {FETCHED}
 * licence  CC BY 4.0. Jumper et al., Nature 596 (2021); Varadi et al.,
 *          Nucleic Acids Research 52 (2024).
 *
 * A prediction, not a measurement. `plddt` is the model's own confidence in
 * each residue, 0 to 100.
 */
(function (root, factory) {{
  var api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  else root.GenomeFold = api;
}})(typeof self !== "undefined" ? self : this, function () {{
  "use strict";
  return {{
    model: "{MODEL}",
    version: {VERSION},
    seq:
{seq_js},
    // x, y, z of each residue's alpha-carbon, in angstroms, residue by residue.
    ca: [
{wrap(coords, 12, "      ")}
    ],
    // The model's confidence in each residue (pLDDT), 0 to 100.
    plddt: [
{wrap([f"{v:.1f}" for v in plddt], 16, "      ")}
    ]
  }};
}});
"""


def main() -> None:
    seq, xyz, plddt = alpha_carbons(fetch().decode("ascii"))
    if not (len(seq) == len(xyz) == len(plddt)) or not seq:
        sys.exit("the model did not parse into one alpha-carbon per residue")
    OUT.write_text(render(seq, xyz, plddt), "utf-8")
    mean = sum(plddt) / len(plddt)
    print(
        f"{OUT.relative_to(ROOT)}: {len(seq)} residues from {MODEL} v{VERSION}, mean pLDDT {mean:.2f}"
    )
    print(f"  source  {URL}")
    print(f"  sha256  {SHA256}")


if __name__ == "__main__":
    main()
